### ISSUE TITLE
首页的运力提示基本没用

### ISSUE THREAD

**Issue by xpring** [czqu/dingdongMonitor#1]
https://maicai.api.ddxq.mobi/homeApi/newDetails这个很不准，可能是更新频率很低，即使显示有运力，下单页面也基本是已约满

**Comment by czqu** [comment]
登录状态下封号风险过大，没办法咯

**Comment by czqu** [comment]
> [https://maicai.api.ddxq.mobi/homeApi/newDetails这个很不准，可能是更新频率很低，即使显示有运力，下单页面也基本是已约满](https://maicai.api.ddxq.mobi/homeApi/newDetails%E8%BF%99%E4%B8%AA%E5%BE%88%E4%B8%8D%E5%87%86%EF%BC%8C%E5%8F%AF%E8%83%BD%E6%98%AF%E6%9B%B4%E6%96%B0%E9%A2%91%E7%8E%87%E5%BE%88%E4%BD%8E%EF%BC%8C%E5%8D%B3%E4%BD%BF%E6%98%BE%E7%A4%BA%E6%9C%89%E8%BF%90%E5%8A%9B%EF%BC%8C%E4%B8%8B%E5%8D%95%E9%A1%B5%E9%9D%A2%E4%B9%9F%E5%9F%BA%E6%9C%AC%E6%98%AF%E5%B7%B2%E7%BA%A6%E6%BB%A1)

登录状态下封号风险过大，没办法咯

**Comment by xpring** [comment]
我的方法是拿没用的号一直扫运力，小黑了停一会儿又能继续用或者换号扫，有运力换主号下单

**Comment by czqu** [comment]
> 我的方法是拿没用的号一直扫运力，小黑了停一会儿又能继续用或者换号扫，有运力换主号下单

我的是彻底封号 无法获取时间了
